steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'smarthaul-ui'
      - '--source'
      - '.'
      - '--region'
      - 'europe-west1'
      - '--project'
      - 'drive-partners2'
      - '--allow-unauthenticated'
