export interface TourStop {
  id: string;
  stopNumber: number;
  facilityCode: string;
  facilityName: string;
  location: string;
  isThirdParty?: boolean; // (3P)
  timeWindow: string;
  actionText: string;
  actionType:
    | 'PICKUP_EMPTY'
    | 'LIVE_LOAD'
    | 'UNLOAD_DEPART_EMPTY'
    | 'SWAP_EMPTY_FOR_LOADED'
    | 'DROP_LOADED'
    | 'SWAP_LOADED_FOR_LOADED'
    | 'SWAP_LOADED_FOR_EMPTY'
    | 'LIVE_UNLOAD';
  trailerStatus: 'EMPTY' | 'LOADED';
  isFlexibleEmptyDrop: boolean;
  flexibilityAdvice?: string;
  approxMilesFromPrev?: number;
  approxDriveMinutes?: number;
  destinationQuery: string;
}

export interface TourShift {
  shiftNumber: number;
  dayName: string;
  dateLabel: string;
  period: string;
  stops: TourStop[];
  totalMilesEst: number;
  totalDriveEst: string;
  layoverHours: number;
  layoverLocation: string;
  layoverText: string;
}

export const AMAZON_RELAY_5DAY_TOUR: TourShift[] = [
  // ─── SHIFT 1: WEDNESDAY ───────────────────────────────────────────────────
  {
    shiftNumber: 1,
    dayName: 'Wednesday',
    dateLabel: 'Day 1 of 5',
    period: 'Early Morning to Afternoon',
    totalMilesEst: 185,
    totalDriveEst: '4h 15m',
    layoverHours: 17,
    layoverLocation: 'Bolton (MAN3)',
    layoverText: 'Daily Rest / Layover: ~17 hrs in Bolton (MAN3) until Thursday morning.',
    stops: [
      {
        id: 'stop-1',
        stopNumber: 1,
        facilityCode: 'STN8',
        facilityName: 'Amazon STN8 Fulfillment Centre',
        location: 'Milton Keynes, Buckinghamshire',
        isThirdParty: false,
        timeWindow: '03:00 – 03:31 BST',
        actionText: 'Pickup empty trailer.',
        actionType: 'PICKUP_EMPTY',
        trailerStatus: 'EMPTY',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Hook up empty box trailer. Ensure rear doors secured.',
        approxMilesFromPrev: 0,
        approxDriveMinutes: 0,
        destinationQuery: 'Amazon STN8 Milton Keynes',
      },
      {
        id: 'stop-2',
        stopNumber: 2,
        facilityCode: 'Whistl',
        facilityName: 'Whistl Distribution Centre (3P)',
        location: 'Wellingborough, Northamptonshire',
        isThirdParty: true,
        timeWindow: '04:30 – 06:01 BST',
        actionText: 'Live load trailer.',
        actionType: 'LIVE_LOAD',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Strict live load appointment slot. Reverse to assigned loading bay.',
        approxMilesFromPrev: 24,
        approxDriveMinutes: 35,
        destinationQuery: 'Whistl Wellingborough',
      },
      {
        id: 'stop-3',
        stopNumber: 3,
        facilityCode: 'BHX7',
        facilityName: 'Amazon BHX7 Hinckley Hub',
        location: 'Hinckley, Leicestershire',
        isThirdParty: false,
        timeWindow: '08:01 – 09:32 BST',
        actionText: 'Unload trailer, depart with empty trailer.',
        actionType: 'UNLOAD_DEPART_EMPTY',
        trailerStatus: 'EMPTY',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: 'Departing with empty trailer. Empty trailers can be dropped early if running ahead.',
        approxMilesFromPrev: 42,
        approxDriveMinutes: 55,
        destinationQuery: 'Amazon BHX7 Hinckley',
      },
      {
        id: 'stop-4',
        stopNumber: 4,
        facilityCode: 'XMA7',
        facilityName: 'XMA Logistics Hub (3P)',
        location: 'Derby, Derbyshire',
        isThirdParty: true,
        timeWindow: '10:42 – 11:30 BST',
        actionText: 'Drop empty trailer, pick up pre-loaded trailer.',
        actionType: 'SWAP_EMPTY_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: '⚡ Anytime Empty Drop: Drop empty trailer in yard anytime. Check pre-loaded trailer seal & height before departure.',
        approxMilesFromPrev: 36,
        approxDriveMinutes: 45,
        destinationQuery: 'XMA Derby Derbyshire',
      },
      {
        id: 'stop-5',
        stopNumber: 5,
        facilityCode: 'MAN3',
        facilityName: 'Amazon MAN3 Distribution Centre',
        location: 'Bolton, Greater Manchester',
        isThirdParty: false,
        timeWindow: '14:01 – 14:41 BST',
        actionText: 'Drop loaded trailer.',
        actionType: 'DROP_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Drop loaded trailer at assigned bay/dock. Shift 1 finished. Commencing 17h daily rest.',
        approxMilesFromPrev: 78,
        approxDriveMinutes: 95,
        destinationQuery: 'Amazon MAN3 Bolton',
      },
    ],
  },

  // ─── SHIFT 2: THURSDAY ────────────────────────────────────────────────────
  {
    shiftNumber: 2,
    dayName: 'Thursday',
    dateLabel: 'Day 2 of 5',
    period: 'Morning to Afternoon',
    totalMilesEst: 228,
    totalDriveEst: '4h 20m',
    layoverHours: 16.5,
    layoverLocation: 'Dunfermline / Aberdeen corridor',
    layoverText: 'Daily Rest / Layover: ~16.5 hrs travel/rest window up to Aberdeen (DAB1).',
    stops: [
      {
        id: 'stop-6',
        stopNumber: 6,
        facilityCode: 'MAN3',
        facilityName: 'Amazon MAN3 Distribution Centre',
        location: 'Bolton, Greater Manchester',
        isThirdParty: false,
        timeWindow: 'Thu, 07:36 – 08:21 BST',
        actionText: 'Pick up pre-loaded trailer.',
        actionType: 'SWAP_EMPTY_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Pre-loaded northbound linehaul trailer. Confirm 5th-wheel lock & brake lines.',
        approxMilesFromPrev: 0,
        approxDriveMinutes: 0,
        destinationQuery: 'Amazon MAN3 Bolton',
      },
      {
        id: 'stop-7',
        stopNumber: 7,
        facilityCode: 'EDI4',
        facilityName: 'Amazon EDI4 Fulfillment Centre',
        location: 'Dunfermline, Fife, Scotland',
        isThirdParty: false,
        timeWindow: 'Thu, 14:30 – 15:11 BST',
        actionText: 'Drop loaded trailer and pick an empty trailer.',
        actionType: 'SWAP_LOADED_FOR_EMPTY',
        trailerStatus: 'EMPTY',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: '⚡ Empty trailer in hand: Can travel and position at DAB1 Aberdeen anytime during rest/buffer.',
        approxMilesFromPrev: 228,
        approxDriveMinutes: 260,
        destinationQuery: 'Amazon EDI4 Dunfermline Fife',
      },
    ],
  },

  // ─── SHIFT 3: FRIDAY ──────────────────────────────────────────────────────
  {
    shiftNumber: 3,
    dayName: 'Friday',
    dateLabel: 'Day 3 of 5',
    period: 'Morning to Evening',
    totalMilesEst: 245,
    totalDriveEst: '4h 45m',
    layoverHours: 11,
    layoverLocation: 'Durham (MME2)',
    layoverText: 'Daily Rest / Layover: ~11 hrs rest in Durham (MME2).',
    stops: [
      {
        id: 'stop-8',
        stopNumber: 8,
        facilityCode: 'DAB1',
        facilityName: 'Amazon DAB1 Delivery Station',
        location: 'Marywell, Aberdeen, Scotland',
        isThirdParty: false,
        timeWindow: 'Fri, 07:48 – 09:15 BST',
        actionText: 'Live load your trailer.',
        actionType: 'LIVE_LOAD',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Live loading southbound parcels. Check axle weights before departing A90.',
        approxMilesFromPrev: 115,
        approxDriveMinutes: 140,
        destinationQuery: 'Amazon DAB1 Marywell Aberdeen',
      },
      {
        id: 'stop-9',
        stopNumber: 9,
        facilityCode: 'MME2',
        facilityName: 'Amazon MME2 Fulfillment Centre',
        location: 'Durham, County Durham',
        isThirdParty: false,
        timeWindow: 'Fri, 16:33 – 17:13 BST',
        actionText: 'Drop off loaded trailer.',
        actionType: 'DROP_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Drop loaded trailer. End of Shift 3. 11 hrs legal daily rest begins.',
        approxMilesFromPrev: 245,
        approxDriveMinutes: 285,
        destinationQuery: 'Amazon MME2 Durham',
      },
    ],
  },

  // ─── SHIFT 4: SATURDAY ────────────────────────────────────────────────────
  {
    shiftNumber: 4,
    dayName: 'Saturday',
    dateLabel: 'Day 4 of 5',
    period: 'Early Morning to Afternoon',
    totalMilesEst: 240,
    totalDriveEst: '4h 30m',
    layoverHours: 12,
    layoverLocation: 'Derby (DNG2)',
    layoverText: 'Daily Rest / Layover: ~12 hrs rest before early Sunday run.',
    stops: [
      {
        id: 'stop-10',
        stopNumber: 10,
        facilityCode: 'MME2',
        facilityName: 'Amazon MME2 Fulfillment Centre',
        location: 'Durham, County Durham',
        isThirdParty: false,
        timeWindow: 'Sat, 04:13 – 04:53 BST',
        actionText: 'Pick up pre-loaded trailer.',
        actionType: 'SWAP_EMPTY_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Pick up loaded trailer heading south on A1(M). Re-verify trailer height on cab HUD.',
        approxMilesFromPrev: 0,
        approxDriveMinutes: 0,
        destinationQuery: 'Amazon MME2 Durham',
      },
      {
        id: 'stop-11',
        stopNumber: 11,
        facilityCode: 'BHX4',
        facilityName: 'Amazon BHX4 Fulfillment Centre',
        location: 'Coventry, West Midlands',
        isThirdParty: false,
        timeWindow: 'Sat, 09:10 – 10:10 BST',
        actionText: 'Drop off loaded trailer and then pick up a pre-loaded trailer.',
        actionType: 'SWAP_LOADED_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Loaded trailer swap. Verify paperwork & seal numbers match app.',
        approxMilesFromPrev: 185,
        approxDriveMinutes: 200,
        destinationQuery: 'Amazon BHX4 Coventry',
      },
      {
        id: 'stop-12',
        stopNumber: 12,
        facilityCode: 'EMA2',
        facilityName: 'Amazon EMA2 Fulfillment Centre',
        location: 'Mansfield, Nottinghamshire',
        isThirdParty: false,
        timeWindow: 'Sat, 12:19 – 13:15 BST',
        actionText: 'Drop off loaded trailer and then pick up a pre-loaded trailer.',
        actionType: 'SWAP_LOADED_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: 'Midlands cross-dock swap. Check M1 bridge clearance along corridor.',
        approxMilesFromPrev: 52,
        approxDriveMinutes: 60,
        destinationQuery: 'Amazon EMA2 Mansfield',
      },
      {
        id: 'stop-13',
        stopNumber: 13,
        facilityCode: 'DNG2',
        facilityName: 'Amazon DNG2 Sortation Centre',
        location: 'Derby, Leicestershire',
        isThirdParty: false,
        timeWindow: 'Sat, 14:10 – 15:26 BST',
        actionText: 'Unload your trailer then depart with an empty trailer.',
        actionType: 'UNLOAD_DEPART_EMPTY',
        trailerStatus: 'EMPTY',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: '⚡ Finished shift with empty trailer. Parked at Derby. 12 hrs rest before Sunday.',
        approxMilesFromPrev: 28,
        approxDriveMinutes: 35,
        destinationQuery: 'Amazon DNG2 Derby',
      },
    ],
  },

  // ─── SHIFT 5: SUNDAY ──────────────────────────────────────────────────────
  {
    shiftNumber: 5,
    dayName: 'Sunday',
    dateLabel: 'Day 5 of 5',
    period: 'Early Morning to Afternoon',
    totalMilesEst: 140,
    totalDriveEst: '3h 15m',
    layoverHours: 0,
    layoverLocation: 'Tour Complete (STN8)',
    layoverText: '5-Day Tour Completed! Return to home base / depot.',
    stops: [
      {
        id: 'stop-14',
        stopNumber: 14,
        facilityCode: 'EMA1',
        facilityName: 'Amazon EMA1 Fulfillment Centre',
        location: 'Derby, East Midlands',
        isThirdParty: false,
        timeWindow: 'Sun, 03:19 – 04:00 BST',
        actionText: 'Drop-off empty trailer and pick up pre-loaded trailer.',
        actionType: 'SWAP_EMPTY_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: '⚡ Anytime Empty Drop: Empty trailer drop is open anytime. Pick up pre-loaded trailer for Northampton.',
        approxMilesFromPrev: 18,
        approxDriveMinutes: 25,
        destinationQuery: 'Amazon EMA1 Derby',
      },
      {
        id: 'stop-15',
        stopNumber: 15,
        facilityCode: 'DNN1',
        facilityName: 'Amazon DNN1 Delivery Station',
        location: 'Northampton, Northamptonshire',
        isThirdParty: false,
        timeWindow: 'Sun, 05:12 – 06:28 BST',
        actionText: 'Unload your trailer then depart with an empty trailer.',
        actionType: 'UNLOAD_DEPART_EMPTY',
        trailerStatus: 'EMPTY',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: '⚡ Empty trailer departing. Can advance to Leighton Buzzard early to avoid morning traffic.',
        approxMilesFromPrev: 54,
        approxDriveMinutes: 65,
        destinationQuery: 'Amazon DNN1 Northampton',
      },
      {
        id: 'stop-16',
        stopNumber: 16,
        facilityCode: 'SWA_CARESUPE',
        facilityName: 'SWA Caresupe Logistics (3P)',
        location: 'Leighton Buzzard, Buckinghamshire',
        isThirdParty: true,
        timeWindow: 'Sun, 07:25 – 11:30 BST',
        actionText: 'Drop-off empty trailer and pick up pre-loaded trailer.',
        actionType: 'SWAP_EMPTY_FOR_LOADED',
        trailerStatus: 'LOADED',
        isFlexibleEmptyDrop: true,
        flexibilityAdvice: '⚡ Generous 4h window. Empty drop accepted early. Hook pre-loaded trailer for final leg into STN8.',
        approxMilesFromPrev: 26,
        approxDriveMinutes: 35,
        destinationQuery: 'Leighton Buzzard Buckinghamshire',
      },
      {
        id: 'stop-17',
        stopNumber: 17,
        facilityCode: 'STN8',
        facilityName: 'Amazon STN8 Fulfillment Centre',
        location: 'Milton Keynes, Buckinghamshire',
        isThirdParty: false,
        timeWindow: 'Sun, 13:30 – 15:00 BST',
        actionText: 'Live unload trailer (Final Stop).',
        actionType: 'LIVE_UNLOAD',
        trailerStatus: 'EMPTY',
        isFlexibleEmptyDrop: false,
        flexibilityAdvice: '🏁 Final stop of the 5-day tour! Reverse onto assigned dock. Hand over consignment notes.',
        approxMilesFromPrev: 14,
        approxDriveMinutes: 20,
        destinationQuery: 'Amazon STN8 Milton Keynes',
      },
    ],
  },
];
